[project]
name = "opmd-pred"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "linexox", email = "linexox7@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "openpyxl>=3.1.5",
    "pillow>=11.0.0",
    "torch>=2.6.0",
    "torchvision>=0.21.0",
    "tqdm>=4.67.1",
]

[project.scripts]
opmd-pred = "opmd_pred:main"

[tool.uv]
index-url = "https://mirrors.aliyun.com/pypi/simple/"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
